[package]
name = "mm"
version = "0.1.0"
authors = ["Emanuel Lima <emanuel-lima@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray-rand = "0.11.0"
ndarray = "0.13.0"
